ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
repository = "umink-core"
owner = "link-mink"
remote = "github.com"
authors = [
    { username = "dfranusic", signature = "Damir Franusic"  }
]

[bump_profiles]
