name: build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install umINK dependencies
      run: |
        sudo apt-get update && \
        apt-get install -y \
        gperf \
        libmosquitto-dev \
        mosquitto-dev \
        libpaho-mqtt-dev \
        liblua5.3-dev \
        libjson-c-dev \
        libcmocka-dev && \
        ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/lua-5.3.pc /usr/lib/x86_64-linux-gnu/pkgconfig/lua.pc
    - name: autogen
      run: ./autogen.sh
    - name: test
      run: pkg-config lua --cflags
    - name: configure
      run: |
        ./configure --enable-mqtt \
                    --enable-mosquitto-auth
    - name: make
      run: make
    - name: make check
      run: make check
