name: github-action-on-push

on:
  push:
    branches:
      - main
      - dev
jobs:
  cog-check-job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3

  build:
    runs-on: ubuntu-latest
    needs: cog-check-job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install umINK dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          gperf \
          libmosquitto-dev \
          mosquitto-dev \
          libpaho-mqtt-dev \
          liblua5.3-dev \
          libjson-c-dev \
          libcmocka-dev && \
          sudo ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/lua-5.3.pc \
          /usr/lib/x86_64-linux-gnu/pkgconfig/lua.pc
      - name: autogen
        run: ./autogen.sh
      - name: test
        run: pkg-config lua --cflags
      - name: configure
        run: |
          ./configure --enable-mqtt \
                      --enable-mosquitto-auth
      - name: make
        run: make
      - name: make check
        run: make check
